### ISSUE TITLE
Exiting windows causes process to hang.

### ISSUE THREAD

**Issue by LukasDauterman** [geoff-va/trackpipe#1]
It looks like run pipe doesn't gracefully exit.

    run_example_1()
  File "test.py", line 60, in run_example_1
    pipeline.run_pipe(transforms)
  File "C:\ProgramData\Anaconda3\lib\site-packages\trackpipe\pipeline.py", line 274, in run_pipe
    k = cv2.waitKey(1) & 0xFF

**Comment by LukasDauterman** [comment]
Looks like there needs to be a way to handle the user exiting, but  the while loop seems to stick around, but I'm not very familiar with how this works.

**Comment by geoff-va** [comment]
Do you mean if you press the x to close a window or push the escape key? I know the escape key will exit the program and close all windows. I’ll need to look up how to handle closing a single window.

**Comment by LukasDauterman** [comment]
I am pressing the x, pressing escape has no issue.

**Comment by geoff-va** [comment]
> Looks like there needs to be a way to handle the user exiting, but the while loop seems to stick around, but I'm not very familiar with how this works.

Yea opencv always seems to having issues when trying to close individual windows if using waitKey. I’ll see if there’s and obvious way to handle exiting the at way. 

Until then hitting escape is your best bet.

**Comment by geoff-va** [comment]
Ok I've made an update that should gracefully exit once all the windows are closed.

Feel free to re-open if you find the problem still exists!
